version: "3.8"
services:
  proxy:
    image: nginx:alpine
    build:
      context: ./
      dockerfile: nginx/Dockerfile
    ports:
      - ${WEB_PORT}

  postgres:
    image: postgres:16.0-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}
    volumes:
      - postgres-data:/var/lib/postgresql/data

  php:
    build:
      context: ../
      dockerfile: /prod/php/Dockerfile
    depends_on:
      - postgres

volumes:
  postgres-data: